--- 
username: admin
password: admin
host: http://localhost:8080/SEMP/v2/config
ok_emoji: üëç
err_emoji: ‚ùå
certs:
  - |
    -----BEGIN CERTIFICATE-----
    MIIFfzCCA2egAwIBAgIJAOFbdgBoLz0qMA0GCSqGSIb3DQEBCwUAMFYxCzAJBgNV
    BAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg
    Q29tcGFueSBMdGQxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0xOTAyMjMwODUxMDZa
    Fw0yMTEyMTMwODUxMDZaMFYxCzAJBgNVBAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0
    IENpdHkxHDAaBgNVBAoME0RlZmF1bHQgQ29tcGFueSBMdGQxEjAQBgNVBAMMCWxv
    Y2FsaG9zdDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN38rzGwd4qo
    FqmOddarlMtnEyhmWW+BUrrtWnWi33TuiCT2EyTvyLUpExdIaskB6a5gq4oAR0zn
    D1Pf6Rvzg8umftxrBYNKYZscqRrsZSAhMOwFWXmtBr8oIpBkinnm3spMdSU7JJaV
    jrLH9orDBaMe5h8Mafi+rfzhL/1mExNY9dBMyopeg5m/RlyPTpjRKmRhCT1PGuaM
    ZSFlkMKU35pn1CcEnSnBcbQGFAYnz2K76eDR7KR/2aaAg0sG9SlfJjIa7yWdMU56
    WNDmeC1ixmgpSjRIJBzGRP8XSbK5a+iOGY3VZhSJijglgGwh1Ngs7rvOWMgM/reb
    OzL04+PCfesHFaJPZz1S9VTxtrZ51Yia1sD08C/PpuJpH5APtScj8wc4sRLcPFun
    /NuWuWFdB1S/ik3Vxy0Ga663scwVQ3GvhHrYn5yrOcAh8yYRQ1MDsyv7etgh3HDc
    ouPVCZRvIsE3uuN1tJeKlcyfoeLzLkQeu+GZA7/vNkh0VvSUjhs8mMyvpGR5Hupk
    sHwnkLkP0gbw3EXcmZh+9F1N5+v18KNG0GGUqKayT1ip6ekBcLKBCVLEh4tQWsQC
    +UN24iRqpyhEOFx57khSbUHwc5/FVPgSARK5YOUZPV08Kz8g4nBG/X59cSNT3fZZ
    srlULpJxEpFpkgFAdeLa5zHeQ+0rYEp7AgMBAAGjUDBOMB0GA1UdDgQWBBQbEPGR
    NfvynTDOJkdamMS3kDb0UTAfBgNVHSMEGDAWgBQbEPGRNfvynTDOJkdamMS3kDb0
    UTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCGri+1HPcz4XZ0MdRr
    rh2cEf5sA32edL90lhiIr1eOjj27bWVU1/kQV3adIuHdLTrTL5kYQGI5Gupo6x5l
    tI41Ad0wKK8w6VyHyMOaiPPHj6nvym9iD0owIGabpp3SaAbhG+1DcBObcWr77Phb
    Lka/1DkR3SqXRAlFbEBg67HoEfJd2lOYH9bjLu0Zhbn+6DFqQ9gPstOTULCr4mxk
    JqOfIGnX8XFsDv2Mm3wWaiqBLonsTcW5iQBf+7WszDhKrs/gs+x45UiCi3ijoH5Q
    Kn5yN6qz9sQozyI8eSip5tj6z18OtsUCvycLvWTOlIi5lsAXo4QqPGtLLEcc52Iz
    mdI0GRBp9mfapB5uuHA+WwZ9zjp/SSEqr7FIJ+CmfF+usP3TsT/8rIGYiLTAVdZ5
    pRVT9Tv6WoOFswkuX++NExc7rsV9cCF4NcujNSxQL4uiX/rsEMF088qeLjkWIB5I
    Dc8zpyE3w2FvPq2tKuLC9/VN9pdiP1+55ygXZFnoHvRIzGncZd7gGd70VwAM7OpF
    0gAk+IPk3oF8UH9KYu9n6tdaRxRj1H0htNDuwyXBaUW/YUFj9lyYRfLlJNkZyhmV
    IfpnWyNbUcBpdeCRQh9fy3z9pkHRXk0c5rmZKMLbXN37bt1d0JYnbjhIH3jB3RSH
    pLhDlG0gmICmW5bIAUQVbtWfbw==
    -----END CERTIFICATE-----